name: calorie_calculator
description: A Flutter app for tracking calories, BMI, and nutritional information.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.5.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  shared_preferences: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/logo.png
    - assets/background.jpg
